nwalkers   = 70        # number of walkers
iterations = 2      # production iterations
burn       = 0       # burn-in iterations
sampler    = "ensemble" # "tempered" (recommended) or "ensemble"
#ntemps     = 1        # number of temperatures (tempered only)
# workers  = 1         # parallel workers (omit for single process)
